language: php
php:
  - 7.1

services:
  - docker

install:
  - docker build --tag test-image .

script:
  - bash test.sh test-image

branches:
  only:
    - master
    - alpine
    - base
    - base-alpine
    - /^[0-9\.]+/
